[versions]

[libraries]
commons-io = "commons-io:commons-io:2.21.0"
guava = "com.google.guava:guava:33.5.0-jre"
junit = "org.junit:junit-bom:5.14.2"

[bundles]

[plugins]
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning-gradle-plugin:7.0.11"
java-qa = "org.danilopianini.gradle-java-qa:1.152.1"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:4.3.2"
publishOnCentral = "org.danilopianini.publish-on-central:9.1.12"
taskTree = "com.dorongold.task-tree:4.0.1"
